import { SCALES } from './theory';
import type { Mood, MusicCue } from './types';

// The character of each cue: key, tempo, harmony and texture. Progressions
// are scale degrees (0 = tonic), one chord per bar.
export const MOODS: Record<MusicCue, Mood> = {
  // Title screen: D major, an unhurried flowing arpeggio.
  menu: {
    bpm: 66,
    beats: 4,
    tonic: 62,
    scale: SCALES.major,
    progressions: [
      [0, 4, 5, 3],
      [0, 5, 3, 4],
      [5, 3, 0, 4],
    ],
    bridge: [
      [3, 0, 4, 5],
      [1, 4, 0, 5],
      [3, 4, 2, 5],
    ],
    lh: 'flow',
    lhBridge: 'broken',
    lhLow: 38,
    melody: [66, 83],
    rest: 0.18,
    motion: 0.35,
    vel: 0.55,
    color: 0.35,
    sparkle: 0.12,
    pedal: 'bar',
  },
  // Chapter I, under the world: A minor waltz, low and sparse.
  roots: {
    bpm: 58,
    beats: 3,
    tonic: 57,
    scale: SCALES.minor,
    progressions: [
      [0, 5, 2, 6],
      [0, 3, 5, 4],
      [0, 6, 5, 6],
    ],
    bridge: [
      [5, 6, 0, 0],
      [3, 4, 0, 0],
      [5, 3, 6, 4],
    ],
    cadence: [6, 0],
    lh: 'flow',
    lhBridge: 'block',
    lhLow: 33,
    melody: [60, 77],
    rest: 0.3,
    motion: 0.25,
    vel: 0.46,
    color: 0.4,
    sparkle: 0.1,
    pedal: 'bar',
  },
  // Forests and clearings: F lydian waltz, bright and airy.
  forest: {
    bpm: 76,
    beats: 3,
    tonic: 65,
    scale: SCALES.lydian,
    // Lydian's major II is the colour; its #iv chord (diminished) is avoided.
    progressions: [
      [0, 1, 0, 4],
      [0, 1, 5, 4],
      [0, 6, 5, 1],
    ],
    bridge: [
      [5, 1, 0, 4],
      [2, 5, 1, 1],
    ],
    lh: 'flow',
    lhBridge: 'broken',
    lhLow: 41,
    melody: [67, 86],
    rest: 0.2,
    motion: 0.45,
    vel: 0.5,
    color: 0.35,
    sparkle: 0.2,
    pedal: 'bar',
  },
  // The ride on the violet horse: D mixolydian, driving eighths.
  ride: {
    bpm: 100,
    beats: 4,
    tonic: 62,
    scale: SCALES.mixolydian,
    progressions: [
      [0, 6, 3, 0],
      [0, 3, 6, 3],
      [0, 6, 5, 6],
    ],
    bridge: [
      [3, 6, 0, 0],
      [5, 6, 3, 0],
    ],
    cadence: [6, 0],
    lh: 'pulse',
    lhBridge: 'flow',
    lhLow: 38,
    melody: [69, 88],
    rest: 0.12,
    motion: 0.7,
    vel: 0.62,
    color: 0.2,
    sparkle: 0,
    pedal: 'half',
  },
  // The Sun: C harmonic minor, low octaves under tense chords.
  sun: {
    bpm: 84,
    beats: 4,
    tonic: 60,
    scale: SCALES.minor,
    raiseLeading: true,
    progressions: [
      [0, 5, 4, 0],
      [0, 3, 4, 4],
      [0, 1, 4, 0],
    ],
    bridge: [
      [5, 3, 4, 4],
      [3, 5, 1, 4],
    ],
    lh: 'ostinato',
    lhBridge: 'pulse',
    lhLow: 36,
    melody: [60, 79],
    rest: 0.25,
    motion: 0.55,
    vel: 0.6,
    color: 0.1,
    sparkle: 0.05,
    pedal: 'half',
  },
  // Inside Gorti: E minor, music-box figures up high.
  inner: {
    bpm: 70,
    beats: 4,
    tonic: 64,
    scale: SCALES.minor,
    progressions: [
      [0, 5, 2, 6],
      [0, 3, 6, 2],
    ],
    bridge: [
      [5, 6, 0, 0],
      [3, 6, 2, 5],
    ],
    cadence: [6, 0],
    lh: 'broken',
    lhBridge: 'flow',
    lhLow: 40,
    melody: [71, 91],
    rest: 0.2,
    motion: 0.5,
    vel: 0.45,
    color: 0.25,
    sparkle: 0.35,
    pedal: 'bar',
  },
  // The empty desk and the ending: A minor, slow chords, few words.
  final: {
    bpm: 54,
    beats: 4,
    tonic: 57,
    scale: SCALES.minor,
    progressions: [
      [5, 6, 0, 0],
      [0, 5, 3, 4],
      [3, 0, 5, 6],
    ],
    bridge: [
      [5, 3, 0, 4],
      [3, 6, 2, 5],
    ],
    cadence: [6, 0],
    lh: 'block',
    lhBridge: 'flow',
    lhLow: 33,
    melody: [64, 81],
    rest: 0.35,
    motion: 0.2,
    vel: 0.42,
    color: 0.5,
    sparkle: 0.1,
    pedal: 'bar',
  },
};
